#!/usr/bin/env bash

# This is intended to be called by the scripts/ci/make/run_task_command wrapper script
# DO NOT try to execute directly, it probably will not work

# All ENVIRONMENT VARIABLES for task are declared in the project Makefile

# Required ENV vars
test "${TEST_IMAGE_NAME:?'required variable'}"

venv_activate
docker-compose -f scripts/ci/docker-compose-ci.yaml down