#!/usr/bin/env bash

# This is intended to be called by the scripts/ci/make/run_task_command wrapper script
# DO NOT try to execute directly, it probably will not work

# All ENVIRONMENT VARIABLES for task are declared in the project Makefile

# Required ENV vars
test "${PYTHON:?'required variable'}"
test "${TEST_DEPS:?'required variable'}"

venv_activate
print_colorized WARN "installing testing dependencies: ${TEST_DEPS[*]}"
for p in ${TEST_DEPS}; do
    hash "$p" || "${PYTHON}" -m pip install -q "$p"
done