#!/usr/bin/env bash

# This is intended to be called by the scripts/ci/make/run_task_command wrapper script
# DO NOT try to execute directly, it probably will not work

# All ENVIRONMENT VARIABLES for task are declared in the project Makefile

# Required ENV vars
test "${VENV:?'required variable'}"

local arch=$(uname | tr A-Z a-z)
local kind_version="v0.7.0"
local kubectl_version="v1.15.0"
local helm_version="v3.1.1"

if [[ ! -x "${VENV}/bin/kind" ]]; then
    print_colorized WARN "installing kind"
    curl -qsSLo "${VENV}/bin/kind" "https://github.com/kubernetes-sigs/kind/releases/download/${kind_version}/kind-${arch}-amd64"
    chmod +x "${VENV}/bin/kind"
fi
if [[ ! -x "${VENV}/bin/helm" ]]; then
    print_colorized WARN "installing helm"
    curl -sSL "https://get.helm.sh/helm-${helm_version}-${arch}-amd64.tar.gz" | tar xzf - -C "${VENV}/bin" --strip-components=1 "${arch}-amd64/helm"
    chmod +x "${VENV}/bin/helm"
fi
if [[ ! -x "${VENV}/bin/kubectl" ]]; then
    print_colorized WARN "installing kubectl"
    curl -sSLo "${VENV}/bin/kubectl" "https://storage.googleapis.com/kubernetes-release/release/${kubectl_version}/bin/${arch}/amd64/kubectl"
    chmod +x "${VENV}/bin/kubectl"
fi