#!/usr/bin/env bash

# This is intended to be called by the scripts/ci/make/run_task_command wrapper script
# DO NOT try to execute directly, it probably will not work

# All ENVIRONMENT VARIABLES for task are declared in the project Makefile

venv_activate
print_colorized WARN "running integration tests"
./scripts/tests/test_with_deps.sh test/integration/
